/*
 * TestResultDetail.java
 *
 */

package com.realtor.rets.compliance.gui;

import com.realtor.rets.compliance.TestResult;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

/** Displays the details of an individual Test Result.
 * @author pobrien
 */
public class TestResultDetail extends JFrame {
    
	private static final int SCROLLPANE_WIDTH = 600;
	private static final int SCROLLPANE_HEIGHT = 90;
	
    private JLabel jLabel8;
    private JLabel jLabel4;
    private JTextArea textJavaException;
    private JScrollPane jScrollPane1;
    private JLabel jLabel1;
    private JLabel jLabel3;
    private JLabel jLabel2;
    private JTextArea textSpecReference;
    private JScrollPane jScrollPane4;
    private JButton jButton1;
    private JTextField textEvaluatorClass;
    private JLabel jLabel9;
    private JScrollPane jScrollPane2;
    private JTextField textStatus;
    private JTextArea textDescription;
    private JLabel jLabel7;
    private JTextArea textNotes;
    private JLabel jLabel6;
    private JScrollPane jScrollPane3;
    private JTextField textTestName;
    private JLabel jLabel5;
      
    /** Constructor that takes a TestResult object as an argument.
     * @param testResult test result to display
     */    
    public TestResultDetail(TestResult testResult) {
        initComponents(testResult);
        setFormFields(testResult);
        
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents(TestResult testResult) {//GEN-BEGIN:initComponents
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jLabel5 = new JLabel();
        jLabel6 = new JLabel();
        textTestName = new JTextField();
        textStatus = new JTextField();
        jScrollPane1 = new JScrollPane();
        textDescription = new JTextArea();
        jScrollPane2 = new JScrollPane();
        textNotes = new JTextArea();
        textEvaluatorClass = new JTextField();
        jScrollPane3 = new JScrollPane();
        textJavaException = new JTextArea();
        jButton1 = new JButton();
        jLabel7 = new JLabel();
        jScrollPane4 = new JScrollPane();
        textSpecReference = new JTextArea();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();

        getContentPane().setLayout(new BorderLayout());

        setTitle("Test Result Detail - " + testResult.getName());
        setResizable(false);
        

        // add title label to top
        JPanel topPanel = new JPanel(new FlowLayout(FlowLayout.CENTER));
        jLabel7.setFont(new Font("Dialog", 1, 18));
        jLabel7.setText("Test Result Detail");
        topPanel.add(jLabel7);
        getContentPane().add(topPanel, BorderLayout.NORTH);

        
        
        // add information panel to the center
        GridBagLayout gbl = new GridBagLayout();
        JPanel infoPanel = new JPanel(gbl);
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(4, 4, 4, 4);
        gbc.anchor = GridBagConstraints.NORTHWEST;
        
        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel1.setText("Test Name");
        infoPanel.add(jLabel1, gbc);
        
        textTestName.setColumns(20);
        textTestName.setEditable(false);
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        infoPanel.add(textTestName, gbc);

        
        

        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel5.setText("Status");
        infoPanel.add(jLabel5, gbc);
        
        textStatus.setColumns(10);
        textStatus.setEditable(false);
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        infoPanel.add(textStatus, gbc);

        
        
        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel2.setText("Description");
        gbl.setConstraints(jLabel2, gbc);
        infoPanel.add(jLabel2);
        
        textDescription.setBackground(getBackground());
        textDescription.setColumns(40);
        textDescription.setEditable(false);
        textDescription.setLineWrap(true);
        jScrollPane1.setPreferredSize(new Dimension(SCROLLPANE_WIDTH, SCROLLPANE_HEIGHT));
        jScrollPane1.setViewportView(textDescription);

        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbl.setConstraints(jScrollPane1, gbc);
        infoPanel.add(jScrollPane1);
        

        
        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel6.setText("Notes");
        gbl.setConstraints(jLabel6, gbc);
        infoPanel.add(jLabel6);
        
        textNotes.setBackground(getBackground());
        textNotes.setColumns(40);
        textNotes.setEditable(false);
        textNotes.setLineWrap(true);
        jScrollPane2.setPreferredSize(new Dimension(SCROLLPANE_WIDTH, SCROLLPANE_HEIGHT));
        jScrollPane2.setViewportView(textNotes);

        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbl.setConstraints(jScrollPane2, gbc);
        infoPanel.add(jScrollPane2);

        

        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel3.setText("Evaluator Class");
        gbl.setConstraints(jLabel3, gbc);
        infoPanel.add(jLabel3);
        

        textEvaluatorClass.setColumns(40);
        textEvaluatorClass.setEditable(false);
        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbl.setConstraints(textEvaluatorClass, gbc);
        infoPanel.add(textEvaluatorClass);

        

        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel4.setText("<HTML>Java<BR>Exception</BR>");
        gbl.setConstraints(jLabel4, gbc);
        infoPanel.add(jLabel4);
        
        textJavaException.setBackground(getBackground());
        textJavaException.setColumns(40);
        textJavaException.setEditable(false);
        textJavaException.setLineWrap(true);
        jScrollPane3.setPreferredSize(new Dimension(SCROLLPANE_WIDTH, SCROLLPANE_HEIGHT));
        jScrollPane3.setViewportView(textJavaException);

        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbl.setConstraints(jScrollPane3, gbc);
        infoPanel.add(jScrollPane3);

        
        
        gbc.gridwidth = GridBagConstraints.RELATIVE;
        jLabel8.setText("<HTML>Specification<BR>Reference</HTML>");
        gbl.setConstraints(jLabel8, gbc);
        infoPanel.add(jLabel8);
        
        textSpecReference.setColumns(40);
        textSpecReference.setBackground(getBackground());
        textSpecReference.setEditable(false);
        jScrollPane4.setPreferredSize(new Dimension(SCROLLPANE_WIDTH, SCROLLPANE_HEIGHT));
        jScrollPane4.setViewportView(textSpecReference);

        gbc.gridwidth = GridBagConstraints.REMAINDER;
        gbl.setConstraints(jScrollPane4, gbc);
        infoPanel.add(jScrollPane4);
        
        
        getContentPane().add(infoPanel, BorderLayout.CENTER);
        
        
        

        // add Close button to the bottom right

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        jButton1.setText("Close");
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonPanel.add(jButton1);
        getContentPane().add(buttonPanel, BorderLayout.SOUTH);
		

        pack();
        setLocationRelativeTo(null);
    }//GEN-END:initComponents

    private void jButton1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /** Sets the GUI form fields from the TestResult object passed in,
     * this is how the results are displayed
     * @param testResult test result to display
     */    
    public void setFormFields(TestResult testResult)
    {
        textTestName.setText(testResult.getName());  
        textDescription.setText(testResult.getDescription());
        textDescription.setCaretPosition(0);
        textNotes.setText(testResult.getNotes());
        textNotes.setCaretPosition(0);
        textEvaluatorClass.setText(testResult.getEvaluatorClass());
        textStatus.setText(testResult.getStatus());
        textJavaException.setText(testResult.getJavaException());
        textJavaException.setCaretPosition(0);
        textSpecReference.setText(testResult.getSpecificationReference());
        textSpecReference.setCaretPosition(0);
       
    }
}
